# Generated by Django 4.1.3 on 2022-11-21 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_modell_remove_producent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modell',
            name='Producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.producent'),
        ),
    ]
