# Generated by Django 4.1.3 on 2022-11-27 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_modell_producent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_strony', models.IntegerField()),
                ('opis_Numer_katalogowy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Katalog_nadrzedny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_katalog', models.TextField()),
                ('modell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.modell')),
            ],
        ),
        migrations.CreateModel(
            name='Numer_katalogowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_strony', models.IntegerField()),
                ('opis_Numer_katalogowy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul_zdiecie', models.TextField()),
                ('opis_zdjecie', models.TextField()),
                ('Wlasciciel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strona_katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_strony', models.IntegerField()),
                ('nazwa_strony', models.TextField()),
                ('katalog_nadrzedny', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.katalog_nadrzedny')),
            ],
        ),
        migrations.CreateModel(
            name='Numer_katalogowy_Czesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_Numer_katalogowy', models.TextField()),
                ('czesc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.czesc')),
                ('numer_katalogowy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.numer_katalogowy')),
            ],
        ),
        migrations.AddField(
            model_name='numer_katalogowy',
            name='Strona_katalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.strona_katalog'),
        ),
        migrations.CreateModel(
            name='GrupaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.BooleanField()),
                ('grupa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.grupa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='czesc',
            name='Strona_katalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.strona_katalog'),
        ),
    ]
