# Generated by Django 4.1.3 on 2022-11-27 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_czesc_katalog_nadrzedny_numer_katalogowy_zdjecie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zdjecie',
            old_name='Wlasciciel',
            new_name='wlasciciel',
        ),
        migrations.AlterField(
            model_name='czesc',
            name='Strona_katalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.strona_katalog'),
        ),
        migrations.AlterField(
            model_name='grupauser',
            name='grupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.grupa'),
        ),
        migrations.AlterField(
            model_name='grupauser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modell',
            name='Producent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.producent'),
        ),
        migrations.AlterField(
            model_name='numer_katalogowy',
            name='Strona_katalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.strona_katalog'),
        ),
        migrations.AlterField(
            model_name='numer_katalogowy_czesc',
            name='czesc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.czesc'),
        ),
        migrations.AlterField(
            model_name='numer_katalogowy_czesc',
            name='numer_katalogowy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.numer_katalogowy'),
        ),
        migrations.AlterField(
            model_name='strona_katalog',
            name='katalog_nadrzedny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.katalog_nadrzedny'),
        ),
    ]
