# Generated by Django 4.1.3 on 2022-11-27 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_remove_katalog_grupa_modell_katalog_grupa_grupa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czesc',
            name='Strona_katalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.strona_katalog'),
        ),
        migrations.AlterField(
            model_name='grupa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupauser',
            name='grupa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.grupa'),
        ),
        migrations.AlterField(
            model_name='grupauser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='katalog_nadrzedny',
            name='katalog_wlascicel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='katalog_nadrzedny',
            name='modell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.modell'),
        ),
        migrations.AlterField(
            model_name='numer_katalogowy',
            name='Strona_katalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.strona_katalog'),
        ),
        migrations.AlterField(
            model_name='numer_katalogowy_czesc',
            name='czesc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.czesc'),
        ),
        migrations.AlterField(
            model_name='numer_katalogowy_czesc',
            name='numer_katalogowy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.numer_katalogowy'),
        ),
        migrations.AlterField(
            model_name='strona_katalog',
            name='katalog_nadrzedny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.katalog_nadrzedny'),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='wlasciciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
