# Generated by Django 4.1.3 on 2022-11-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_czesc_strona_katalog_alter_grupa_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numer_katalogowy',
            old_name='Strona_katalog',
            new_name='strona_katalog',
        ),
    ]
