# Generated by Django 4.1.3 on 2022-11-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_strona_katalog_numer_katalogowy_strona_katalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numer_katalogowy',
            old_name='numer_strony',
            new_name='numer_katalogowy_strona',
        ),
    ]
