# Generated by Django 4.1.3 on 2022-11-28 22:30

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_opis_numer_katalogowy_numer_katalogowy_czesc_opis_numer_katalogowy_czesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdjecie',
            name='mage_url',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_to),
        ),
    ]
