# Generated by Django 4.1.3 on 2022-11-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_zdjecie_mage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zdjecie',
            old_name='mage_url',
            new_name='image_url',
        ),
    ]
