# Generated by Django 4.1.3 on 2022-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_mage_url_zdjecie_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zdjecie',
            name='image_url',
        ),
    ]
