# Generated by Django 4.1.3 on 2022-11-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_zdjecie_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zdjecie',
            old_name='image_url',
            new_name='image',
        ),
    ]
