# Generated by Django 4.1.3 on 2022-11-30 21:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_image_url_zdjecie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
    ]
