# Generated by Django 4.1.3 on 2023-01-07 10:46

import base.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_zdjecie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog_nadrzedny',
            name='opis_katalog',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=base.models.upload_to),
        ),
    ]
