# Generated by Django 4.1.3 on 2023-01-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_katalog_nadrzedny_opis_katalog_alter_zdjecie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='strona_katalog',
            name='zdjecie_strona_katalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.zdjecie'),
        ),
    ]
