# Generated by Django 4.1.3 on 2023-01-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_strona_katalog_zdjecie_strona_katalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='czesc',
            name='numer_katalogowy',
        ),
    ]
