# Generated by Django 4.1.3 on 2023-01-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_czesc_numer_katalogowy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zdjecie',
            name='tytul_zdiecie',
        ),
    ]
