# Generated by Django 4.1.3 on 2023-01-16 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0025_remove_zdjecie_tytul_zdiecie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_lista', models.TextField()),
                ('numer_katalogowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.numer_katalogowy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Numer_katalogowy_Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lista')),
                ('numer_katalogowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.numer_katalogowy')),
            ],
        ),
    ]
