# Generated by Django 4.1.3 on 2023-01-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_lista_numer_katalogowy_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='numer_katalogowy',
        ),
    ]
