# Generated by Django 4.1.3 on 2023-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_lista_numer_katalogowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='numer_katalogowy_lista',
            name='liczba',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
