# Generated by Django 4.1.3 on 2023-02-24 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0029_numer_katalogowy_czesc_liczba_numer_katalogowy_czesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupauser',
            name='grupa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.grupa'),
        ),
        migrations.AlterField(
            model_name='grupauser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
